apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: large-file-storage-system
  description: Large File Storage System
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: kubecon-squad
  system: storage
